language: go

go: 
  - 1.5
  - 1.6
  - 1.7
  
before_script:
  # static code analysis
  - go vet

script:
  - go test -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
